version: "0.0.1"
services:
  backend:
    image: ghcr.io/torfstack/kayvault-backend:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - $PWD/kayvault.json:/kayvault.json