services:
  kayvault:
    container_name: kayvault
    image: kayvault:local
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-debug
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    ports:
      - "4000:4000"
      - "4200:4200"
    depends_on:
      kayvault-db:
        condition: service_healthy
  kayvault-db:
    container_name: kayvault-db
    image: postgres:latest
    environment:
      POSTGRES_USER: kayvault
      POSTGRES_PASSWORD: kayvaultpass
      POSTGRES_DB: kayvaultdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "4100:5432"