apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayvault-backend-deployment
  labels:
    app: kayvault-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kayvault-backend
  template:
    metadata:
      labels:
        app: kayvault-backend
    spec:
      containers:
        - name: kayvault-backend
          image: ghcr.io/torfstack/kayvault-backend:0.0.2
          ports:
            - containerPort: 4000
              hostPort: 4000
          volumeMounts:
            - mountPath: "/opt/kayvault/kayvault.json"
              subPath: "kayvault.json"
              name: secret-kayvault-json
              readOnly: true
      volumes:
        - name: secret-kayvault-json
          secret:
            secretName: kayvault-json
      imagePullSecrets:
        - name: regcred
