version: '3'

vars:
  NEXT_VERSION: 
    sh: sh next_version

tasks:
  backend-test:
    dir: backend
    cmds:
      - cmd: go test ./...
  backend-release:
    dir: backend
    requires:
      vars: [IMAGE_TAG]
    cmds:
      - cmd: docker buildx build -t ghcr.io/torfstack/kayvault-backend:{{.IMAGE_TAG}} .
      - cmd: docker push ghcr.io/torfstack/kayvault-backend:{{.IMAGE_TAG}}
  frontend-release:
    dir: frontend
    requires:
      vars: [IMAGE_TAG]
    cmds:
      - cmd: docker buildx build -t ghcr.io/torfstack/kayvault-frontend:{{.IMAGE_TAG}} .
      - cmd: docker push ghcr.io/torfstack/kayvault-frontend:{{.IMAGE_TAG}}
  deploy:
    requires:
      vars: [IMAGE_TAG]
    cmds:
      - cmd: helm upgrade --install kayvault deployment --set backend.tag={{.IMAGE_TAG}} --set frontend.tag={{.IMAGE_TAG}}
  dev-deploy:
    vars:
      DEV_IMAGE_TAG: development
    cmds:
      - task: backend-release
        vars:
          IMAGE_TAG:
            ref: .DEV_IMAGE_TAG
      - task: frontend-release
        vars:
          IMAGE_TAG:
            ref: .DEV_IMAGE_TAG
      - task: deploy
        vars:
          IMAGE_TAG:
            ref: .DEV_IMAGE_TAG
  release:
    cmds:
      - task: backend-release
        vars:
          IMAGE_TAG:
            ref: .NEXT_VERSION
      - task: frontend-release
        vars:
          IMAGE_TAG:
            ref: .NEXT_VERSION
      - task: deploy
        vars:
          IMAGE_TAG:
            ref: .NEXT_VERSION

