version: '3'

tasks:
  backend-build:
    dir: backend
    cmds:
      - docker buildx build -t ghcr.io/torfstack/kayvault-backend:0.0.6 .
      - docker push ghcr.io/torfstack/kayvault-backend:0.0.6
  backend-test:
    dir: backend
    cmds:
      - go test ./...
  frontend-build:
    dir: frontend
    cmds:
      - docker buildx build -t ghcr.io/torfstack/kayvault-frontend:0.0.2 .
      - docker push ghcr.io/torfstack/kayvault-frontend:0.0.2
  build:
    cmds:
      - task: build-backend
      - task: build-frontend
  deploy:
    cmds:
      - helm upgrade --install kayvault deployment
