version: '3'

vars:
  IMAGE_TAG: 
    sh: sh next_version
  VERSION_TO_DEPLOY:
    sh: git tag --sort=-creatordate | head -n 1

tasks:
  test:
    cmds:
      - cmd: go test ./...
  start-local:
    cmds:
      - cmd: npm run --prefix frontend build
      - cmd: mv frontend/build/ static/
      - cmd: go build -o bin/kayvault cmd/main.go
      - cmd: ./bin/kayvault
  release:
    requires:
      vars: [IMAGE_TAG]
    cmds:
      - cmd: docker buildx build -t ghcr.io/torfstack/kayvault:{{.IMAGE_TAG}} .
      - cmd: docker push ghcr.io/torfstack/kayvault:{{.IMAGE_TAG}}
  deploy:
    requires:
      vars: [VERSION_TO_DEPLOY]
    cmds:
      - cmd: helm upgrade --install kayvault deployment --set tag={{.VERSION_TO_DEPLOY}}
  dev-deploy:
    vars:
      DEV_IMAGE_TAG: development
    cmds:
      - task: release
        vars:
          IMAGE_TAG:
            ref: .DEV_IMAGE_TAG
      - task: deploy
        vars:
          VERSION_TO_DEPLOY:
            ref: .DEV_IMAGE_TAG
