version: '3'

dotenv: ['versions']

tasks:
  backend-build:
    dir: backend
    cmds:
      - cmd: docker buildx build -t ghcr.io/torfstack/kayvault-backend:$NEXT_BACKEND_VERSION .
  backend-test:
    dir: backend
    cmds:
      - cmd: go test ./...
  backend-release:
    dir: backend
    cmds:
      - task: backend-build
      - cmd: docker push ghcr.io/torfstack/kayvault-backend:$NEXT_BACKEND_VERSION
  frontend-build:
    dir: frontend
    cmds:
      - cmd: docker buildx build -t ghcr.io/torfstack/kayvault-frontend:$NEXT_FRONTEND_VERSION .
  frontend-release:
    dir: frontend
    cmds:
      - task: frontend-build
      - cmd: docker push ghcr.io/torfstack/kayvault-frontend:$NEXT_FRONTEND_VERSION
  deploy:
    cmds:
      - cmd: helm upgrade --install kayvault deployment
  release:
    cmds:
      - task: backend-release
      - task: frontend-release
      - task: deploy

