apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: config-yaml
          secret:
            secretName: kayvault
      containers:
        - name: kayvault-backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              hostPort: 4000
          volumeMounts:
            - mountPath: "/config.yaml"
              subPath: "config.yaml"
              name: config-yaml
              readOnly: true
        - name: kayvault-frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              hostPort: 3000
      imagePullSecrets:
        - name: regcred
  strategy:
    type: Recreate
