spring:
  datasource:
    url: "jdbc:h2:./build/run"
    username: "kayvault"
    password: "password"
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
server:
  port: 4000
