name: docker-build
run-name: ${{ github.actor }} is building the kayvault backend docker image

on:
  push:
    branches:
      - 'main'

jobs:
  build-it:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: test
        run: ./gradlew clean test
        working-directory: ./backend
      - name: release
        run: ./buildit
        working-directory: ./backend

