name: pr-checks
run-name: ${{ github.actor }} is running pr checks

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'
      - name: install task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: test backend
        run: task backend-test
  linter:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'
      - name: lint backend
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: backend

