name: release
run-name: ${{ github.actor }} is releasing a new version

on:
  push:
    branches:
      - 'main'

jobs:
  release-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: setup docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: release backend
        run: task backend-release
      - name: release frontend
        run: task frontend-release
      - name: create git tag
        run: |
          next_version=$(sh next_version)
          git tag $next_version
          git push --tags

