name: build-frontend
run-name: ${{ github.actor }} is building the kayvault frontend docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - frontend/**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: release frontend
        run: task frontend-release

