name: release
run-name: ${{ github.actor }} is releasing a new version

on:
  push:
    branches:
      - 'main'

jobs:
  release-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'
      - name: install task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: test backend
        run: task backend-test
      - name: release backend
        run: task backend-release

